<?php
use WeatherMaster\Helpers\PathHelper;

$stylePath = PathHelper::getAbsolutePath("assets/css/style.css");
$faviconPath = PathHelper::getAbsolutePath("assets/favicon");
$scriptsPath = PathHelper::getAbsolutePath("assets/scripts");

$indexPath = "/";
$weeklyForecastPath = "/weekly";
$guestbookPath = "/guestbook";
$chatPath = "/chat";
$strategyPath = "/strategy";
$adapterPath = "/adapter";
$loginPath = "/auth/login";
$logoutPath = "/auth/logout";
$adminPath = "/admin";

$title = $pageTitle ?? 'Weather Master';
$date = date("Y");
?>
<!doctype html>
<html lang="uk">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><?= htmlspecialchars($title) ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="<?= $stylePath ?>">
    <link rel="apple-touch-icon" sizes="180x180" href="<?= $faviconPath ?>/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="<?= $faviconPath ?>/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="<?= $faviconPath ?>/favicon-16x16.png">
    <link rel="manifest" href="<?= $faviconPath ?>/site.webmanifest">
</head>

<body>
    <div class="wrapper">
        <header class="header border-bottom">
            <div class="container">
                <div class="header__wrap py-4">
                    <a href="<?= $indexPath ?>"
                        class="header__logo d-flex align-items-center link-body-emphasis text-decoration-none">
                        <i class="bi bi-umbrella header__logo-icon" aria-hidden="true"></i>
                        <span class="fs-4 header__logo-text">Weather Master</span>
                    </a>
                    <nav>
                        <ul class="nav nav-pills align-items-center">
                            <li class="nav-item"><a href="<?= $indexPath ?>" class="nav-link"
                                    aria-current="page">Головна</a></li>
                            <li class="nav-item"><a href="<?= $weeklyForecastPath ?>" class="nav-link">Прогноз</a></li>
                            <li class="nav-item dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                    Додаткові функції
                                </button>
                                <ul class="dropdown-menu">
                                    <li class="nav-item"><a class="dropdown-item" href="<?= $guestbookPath ?>"
                                            class="nav-link text-success">Гостьова</a></li>
                                    <li class="nav-item"><a class="dropdown-item" href="<?= $strategyPath ?>"
                                            class="nav-link text-success">Стратегія</a></li>
                                    <li class="nav-item"><a class="dropdown-item" href="<?= $adapterPath ?>"
                                            class="nav-link text-success">Патерн Adapter</a></li>
                                    <li class="nav-item"><a class="dropdown-item" href="<?= $chatPath ?>"
                                            class="nav-link text-primary"><i class="bi bi-chat-fill"></i> Чат</a></li>
                                </ul>
                            </li>

                            <?php if (isset($_SESSION['admin_logged_in'])): ?>
                                <li class="nav-item"><a href="<?= $adminPath ?>" class="nav-link">Адміністрування</a></li>
                                <li class="nav-item"><a href="<?= $logoutPath ?>" class="nav-link active-danger">Вийти</a>
                                </li>
                            <?php else: ?>
                                <li class="nav-item"><a href="<?= $loginPath ?>" class="nav-link active">Увійти</a></li>
                            <?php endif; ?>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <main class="main"><?= $content ?></main>
        <footer class="footer py-4 mt-4">
            <div class="container">
                <nav>
                    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                        <li class="nav-item"><a href="<?= $indexPath ?>" class="nav-link px-2">Головна</a></li>
                        <li class="nav-item"><a href="<?= $weeklyForecastPath ?>" class="nav-link px-2">Щотижневий
                                прогноз</a>
                        </li>
                    </ul>
                </nav>
                <div class="d-flex flex-column flex-sm-row justify-content-between align-items-center pt-2">
                    <p class="footer__copyright">©
                        <?= $date ?> Weather Master
                    </p>
                    <ul class="footer__social list-unstyled d-flex mb-0 mt-3 mt-sm-0">
                        <li class="ms-3">
                            <a class="footer__social-link" href="mailto:bohdan.shcherbak1@nure.ua"
                                aria-label="Email нам">
                                <i class="bi bi-envelope-fill"></i>
                            </a>
                        </li>
                        <li class="ms-3">
                            <a class="footer__social-link" href="https://discord.gg/XJGmJ8Jg9" target="_blank"
                                aria-label="Наш Discord сервер">
                                <i class="bi bi-discord"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </footer>

        <div class="weather-toast-container toast-container position-fixed bottom-0 end-0">
            <div id="liveAlertToast" class="toast text-bg-warning border-0" role="alert" aria-live="assertive"
                aria-atomic="true">
                <div class="toast-header bg-warning text-dark border-bottom border-dark-subtle">
                    <i class="bi bi-bell-fill me-2"></i>
                    <strong class="me-auto">Нове повідомлення!</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
                <div class="toast-body" id="toast-body-content"></div>
            </div>
        </div>

    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"></script>
    <script src="<?= $scriptsPath ?>/alert.js" defer></script>
</body>

</html>